### ISSUE TITLE
Step by step guide?

### ISSUE THREAD

**Issue by pangelovski** [jonassjoh/dspW245#3]
Hi Jonas, 
Thanks for making this happen. However, I cannot seem to figure out how I am supposed to get it running on Home Assistant. I added the "dspW245.py" to my /config/python_script folder and I also created a new file call dlink_plug.py and then pasted in your script. But what's the next step? I also noticed from reading that HA will have issues with the import statement. Can you please provide how this is supposed to work?

**Comment by jonassjoh** [comment]
I am not familiar with how Home Assistant works and did not write it to be compatible with it.
I will personally most likely never make any changes to the code for this project, much less so to make it compatible with HA. Any required changes would thus have to be made by someone else or yourself.

I've been told that most people seem to use HA to interface with similar devices so should you manage to get it to work with HA I'd be interested to know. If so I can update this repository to point others in the right direction.

The code should work when running it on it's own.
