### ISSUE TITLE
Support for DSP-W118?

### ISSUE THREAD

**Issue by Vinz87** [jonassjoh/dspW245#4]
Hi, would it be possible to add support for DSP-W118 smart plug?

**Comment by Garfonso** [comment]
did you try it? For the DSP-W115 it just worked.

**Comment by jonassjoh** [comment]
What happens when you try to interface with the device? If you can share the output it may shed some more light on the issue.
You can get more verbose output like this:
```
SmartPlug(HOST, pin, verbose=2)
```

As of now I do not have any plans of making any changes to this repository, and I will probably not in the future either. So if you cannot get it to work as it is now, I'm guessing you won't get it to work with minor changes either.

**Comment by markuspalme** [comment]
This is what I get:

```
Traceback (most recent call last):
  File ".\test.python", line 5, in <module>
    sp = SmartPlug("192.168.178.100", "xxxxxxxx", verbose=2)
  File "C:\Users\marku\source\Repos\dlink\dspW245.py", line 191, in __init__
    self.connect()
  File "C:\Users\marku\source\Repos\dlink\dspW245.py", line 199, in connect
    self.socket.connect((self.host, self.port))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1342, in connect
    self._real_connect(addr, False)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1329, in _real_connect
    super().connect(addr)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

**Comment by jonassjoh** [comment]
Based on the error I'm afraid it looks like your device is not compatible with this library. As a result I'll close this issue.

If you manage to find a library/solution that works for your device, I'd be interested to know so that I can point others in the correct direction.

**Comment by oniongarlic** [comment]
This is what I get from my W118.
```
Sending HTTP upgrade request
Recieved:
"b'HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: dzHFToSz8oZZAqJsC3eXymFEs7c=\r\n\r\n'"

Sending sign_in to get salt
Recieved:
"{
	"command":	"sign_in",
	"sequence_id":	1001,
	"salt":	"2d61dadec7d3b991edb9e571ebe74aa5",
	"init":	0,
	"code":	0,
	"message":	"no error",
	"device_id":	"60634C280541"
}"

Sending get device status
Traceback (most recent call last):
  File "dspW245.py", line 366, in <module>
    sp.device_status()
  File "dspW245.py", line 270, in device_status
    self.send_json(data, log="Sending get device status")
  File "dspW245.py", line 245, in send_json
    r = self.send(data, log)
  File "dspW245.py", line 205, in send
    r = self.recv(raw)
  File "dspW245.py", line 216, in recv
    return self.socket.recv(1024) if raw else self.parser.decode(_recv)
  File "dspW245.py", line 164, in decode
    self.parseOpCode(data(1))
  File "dspW245.py", line 214, in _recv
    r = [d for d in self.socket.recv(n)]
  File "/usr/lib/python3.6/ssl.py", line 997, in recv
    return self.read(buflen)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 633, in read
    v = self._sslobj.read(len)
socket.timeout: The read operation timed out

```

**Comment by jonassjoh** [comment]
@oniongarlic Interesting. This suggests that the device may actually be compatible after all, since the `sign_in` command looks good.
Can you get any of the other commands to work, like `set_led`?

**Comment by jonassjoh** [comment]
Hmm. It's weird that it doesn't recieve a response for any of the other commands considering two of them appear to work just fine. I'm not sure what's going on here.

I must admit I'm a bit curious, but I unfortunally don't really have the time to peek in the firmware for the w118 to see what's going on. However, if you (or anyone else) have access to the `da_adaptor` binary in the firmware, would you mind sharing it if I ever get around to having a look?
