### ISSUE TITLE
Firmware and hardware versions compatibility

### ISSUE THREAD

**Issue by gralin** [jonassjoh/dspW245#5]
Hi! In the readme it's written that you have tested DSP-W245 with firmware versions:

* 3.0.0-b45
* 3.3.0-b03

My DSP-W245 shows firmware **1.00-b23**. In the mobile app I get prompted to update the firmware but later when it's finished I still see the same firmware number (and app prompts again to upgrade, same each time I try). I am wondering if maybe I have some old hardware version which can't be upgraded to firmware v3? What is the H/W version you guys have? I can't find anything about this online, I will try to ask D-Link in the meantime but would be grateful if someone could share your hardware version numbers or point me to what I need to do to be able to upgrade.

![image](https://user-images.githubusercontent.com/3457048/102936195-055b5c00-44a8-11eb-903c-b0d2bf72c6a8.png)

**Comment by jonassjoh** [comment]
On the back of my device it also says hardware version A1 and firmware version 1.00. This should not be an issue. I also belive that I tried your firmware version aswell, but I cannot remember for certain.
I don't know why your device fails to update.

Are you having issues using this library?

**Comment by gralin** [comment]
Hi @jonassjoh, at first I was having timeouts so I figured I need to stop any further tests and focus on getting the same firmware as you. This took me hours now and I still didn't manage to figure out how to upgrade... The app shows me the latest availavle is v1.01 but after performing upgrade nothing happens and it always stays that way. So weird that the latest is not the same as you are using and that I can't upgrade to it. Maybe there is some difference with versions based on region? (mine is Europe).

However, I took a step back and tried again if maybe this firmware will still work and it seems that I must have had some other type of issue at first becuase yes, it works! First I tried while directly connected to the device self hosted wifi, and later paired it with my wifi, works in both cases. But I'm super frustrated with this device because it takes several attempts to pair it with my house wifi (based on Ubiquiti APs and Cisco router). I wrote to DLink and got support ticket opened, will share here anything they write me back about this.

BTW. does your device also fail to start if you quickly disconnect it from power source and connect back in? I need to wait a few seconds and then connect back, only then it boots... I have looked hard to find some nice power strip which would not be Chinese (Taiwan, though seen as Chine by some, is already an upgrade) but it seems that Sonoff would be a better choice after all.

**Comment by gralin** [comment]
Oh, an in my firmware I can only see these ports open, regardless if I connect directly to device wifi or when device is paired with my wifi. There is no telnet port which was described in README (maybe only firmware v3 has it?)

![image](https://user-images.githubusercontent.com/3457048/102944496-3ee99280-44bb-11eb-843d-896ff12bbb14.png)

**Comment by jonassjoh** [comment]
The telnet service is only available when the device is in recovery mode (see readme).

I updated the readme to clarify the firmware versions. They are called different things at certain points and I picked the not so clear option. You are on 3.0.0-b45, which is also known as 1.00.

If you want to download the newer firmware to try and manually install it you can download it here (just note that this always comes with some risk): https://mydlinkmpfw.auto.mydlink.com/DSP-W245/DSPW245_A1_FW101b03.bin

Honestly, I had so much trouble with the device when I was working with it. I found ways to get around the issues I had with connectivity etc. that worked for me, but it was always a hassle. I had to factory reset the device so many times during experimentation. Knowing what I know now, I would NOT buy the device myself. I never enjoyed the app either.

**Comment by gralin** [comment]
Thank you for the links to firmware, I was looking all over Internet for this but seems that your skills are better. Now I will try to use your script to update as apparently it can't be done the official way. If I brick it, I can still return it, I will just claim it was like this when I got it 👼 I was also thinking about returning it anyway becuase of all the problems. Worst thing is the situation when it doesn't boot when I connect it to power, do you experience something like this too? If I return it I will just take a regular power strip and stick several simple smart plugs with Tasmota, I will get the same effect just with multiple wifi clients.

As for telnet, I tried to use the way you described in readme of course, but I failed. I now found in [release notes](https://github.com/jonassjoh/dspW245/files/5737104/DSP-W245_A1_FW_V1.01b03_Release_Note_20190926.pdf), that telnet got removed in my firmware version.

**Comment by jonassjoh** [comment]
The download center was not easy to find lol, which is another reason that I don't really like the device. The firmware download link I only found deep within the firmware.

Whenever my device lost power I was not able to get it to boot again, which was incredibly frustrating. I later found that if I left the device unplugged for about half an hour (or sometimes longer) it would suddenly boot when I plugged it back in. I don't know if there was any aspect of the device that **didn't** bring up issues.

It's hilarious that you have to resort to using this library to update your device. Yikes.

Can you spawn a telnet service on this version?

**Comment by gralin** [comment]
I feel you, I have the same with my device. I need to leave it for a bit unplugged and only then it boots correctly. What is also frustrating is that it doesn't remember the last settings once the power is back.

> I don't know if there was any aspect of the device that didn't bring up issues.

I have the exact same feeling now

> Can you spawn a telnet service on this version?

To be honest, now that I have it paired with my home wifi and tucked it away, I am a bit lazy to restore it to factory default to check this, knowing what a hustle it is to pair it again (sometimes I had to do it more than once to get it paired). Which firmware version were you using when you confirmed that telnet was working? The ones you listed in readme?

Also, congratz on the reverse engineering of firmware btw, not an easy task. Did you also try to sniff the websocket traffic with man-in-the-middle approach? I am wondering if the device validates TLS certificate or not. This would allow for easier analysis of the commands used and their message format. For example, I was thinking about adding the watt consumption, and knowing it exists in the app, it has to be queried and send by device, propably via the websocket connection using the json formatted messages we already know?.

**Comment by jonassjoh** [comment]
>  I am a bit lazy to restore it to factory default knowing what a hustle it is to pair it again.

Fair enough, I was just curious :p

> Which firmware version were you using when you confirmed that telnet was working? The ones you listed in readme?

Yes. Both.

> Did you try to sniff the websocket traffic?

Yes. The first few messages are sent using HTTPS, but after that you need to decrypt the traffic using the HybiParser, which is hard to know without disassembling the firmware, or android application. Once you have the HybiParser, you can read the traffic to and from the device in plain JSON text.

If you want to read the traffic yourself you need your devices private key and the password for it.
The certificates used for the HTTPS connection is stored in `/mydlink/cert/`. You can get the password for the private key using the following snippet of Python code:

```
def da_cfg_ssl_passwd_cb():
  from hashlib import md5
  pw = '00000000' # Replace this with your mydlink_no
  pw = pw[::-1]
  pw = pw + ''.join(map(chr, [0x4b,0x62,0x32,0x67,0x37,0x58,0x39,0x75]))
  pw = md5(pw.encode('utf-8')).hexdigest()
  pw = md5(pw.encode('utf-8')).hexdigest()
  return pw
```

**Comment by jonassjoh** [comment]
I guess I'll close this issue. I read through it and I believe everything is resolved? Atleast the things that can be resolved.

If you, or someone else, is still having some issue/problem, feel free to comment or open a new issue.

**Comment by gralin** [comment]
Sure, thank you for your support with this!

I decided to keep the power strip and experiment with it in my spare time. When my patience grows thin I will simply replace it with something else and leave it to control a lightbulb instead, as I won't trust it to control anything more ;) Maybe you could enable GitHub Discussions in this repo so that I can ask questions there instead of openning issues? (as I don't have any issues that need resolving, unless you consider a question and issue and response a way to resolve it).

**Comment by jonassjoh** [comment]
I went ahead and enabled Discussions if you prefer to ask questions there. I mainly consider issues things that directly affect the usage of the repository itself. Questions about, for example, how to sniff the network traffic are perhaps better suited for the Discussion section. Nevertheless, I'll happily answer questions regardless of where they are posted.
